### ISSUE TITLE
Q. TypeOrm사용 해서 Schemas 생성 관련.

### ISSUE THREAD

**Issue by maindishes** [42-TRANSENDENCE/backend#14]
현재 데이터 베이스에 직접 접근해서 Schemas  를 직접 생성해 줘야 연결이 되는데 이부분  TypeOrm 으로 생성 할수 있는지 ? 
```ts
export class TypeOrmConfigService implements TypeOrmOptionsFactory {
  constructor(private configService: ConfigService) {}
  createTypeOrmOptions(): TypeOrmModuleOptions {
    return {
      type: 'postgres',
      host: this.configService.get('DB_HOST'),
      port: +this.configService.get('DB_PORT'),
      username: this.configService.get('DB_USER_NAME'),
      password: this.configService.get('DB_PASSWORD'),
      database: this.configService.get('DB_DATABASE'),
      entities: [__dirname + '/../**/*.entity.{js,ts}',
      Chats,],
      synchronize: true,
      schema: 'j_test',
    };
```
- 찾아보닌까 맨 아래  `schema: 'j_test',`  이런식으로 추가 하면 된다는데  그래도 생성 되지 않음.

**Comment by minjune8506** [comment]
schema를 왜 만드려고 하는거에요?
저 옵션 자체를 처음보는디

**Comment by maindishes** [comment]
나중에 테이블 많아지면 이름 겹치는 거나 또 권한따로 설정해주고 테이블 join할때 확장성에 좋다던데 저렇게 Specifying 하게 하면 나중에 필요하면 저렇게 하고 일단 Public 스키마에 고우?

**Comment by minjune8506** [comment]
https://typeorm.io/data-source-options#common-data-source-options
여기서 찾아보고있는데 딱히 안보이는데.. 어떤건지 잘 모르겠어요
어디 써져있는거있으면 찾아서 알려주세요

**Comment by minjune8506** [comment]
schema - Schema name. Default is "public".
이렇게 있긴하네요

**Comment by minjune8506** [comment]
entity에서 저렇게 해놓으면 알아서 다 검색해서 Chats를 따로 추가할 필요가 없을거에요

**Comment by maindishes** [comment]
그럼 public에 하는걸로 코드 수정 하고 나중에 문제 생기면 그때 생각해보는걸로 하고 이슈 닫겠습니다 ~

**Comment by maindishes** [comment]
일단 Public 에 다 하고 추후 문제 생길시 나누는걸로
