### ISSUE TITLE
import , provider 최적화 

### ISSUE THREAD

**Issue by maindishes** [42-TRANSENDENCE/backend#140]
- 모듈당 컨테이너에 올릴수있는거 올려놓고 DI잘 활용해서 import 하는거 최소화 하기 ? (이게 필요할까?)

**Comment by minjune8506** [comment]
export import 활용 제대로 못하면 객체 여러개 생성돼서 문제가 발생할수도 이씁니다.

**Comment by maindishes** [comment]
객체 여러개 생성되는거는 요청 횟수로 확인할수있는건가요 ? 한번 provider 잘못 활용해서 socket객체가 2개 생성 된적있긴 했었는데

**Comment by minjune8506** [comment]
저는 compodoc 이거 쓸때 확인했었느데 그냥 module import만 잘하면 왠만하면 그 문제 안생길듯요
