### ISSUE TITLE
밴리스트 DB 만들기 vs Redis 로 관리하기

### ISSUE THREAD

**Issue by maindishes** [42-TRANSENDENCE/backend#72]
# Redis로 해야  시간 관련한걸 쓸수 있다.  (TTL)

- Redis 는 없어져도 되는 정보들?
- Redis를 쓴다고 DB를 안 쓰는건 아니다.
- 결론은 밴리스트 DB + Redis(TTL)
-  Ban 이랑 Kick은 시간만 달라진다고 치면 mutelist는 .. ? 이건 Redis로 만 해야하겠지? 
- 어차피 DB다 만들어져있는데 시간 관리만을 위해 redis 쓰는건 아닌거 같아서 안 쓰는 걸로 한다 . 설정 어려워서가 아닌걸로 ~ [참고](https://tre2man.tistory.com/277)
-------
- [x] 일단 Ban + Kick 구현 -> 사실 Ban 하나인데 Redis로 Ban 은 시간 무한대로 하고 Kick은 일단 테스트 용으로 (10초)
  - [x] banlist 에 있으면 채팅방 입장 못하게 하는거
- [x]  mute  도 디비 생성, api 구현  테스트로 (10초)
  - [x] mute 리스트에 있으면 채팅 디비에 저장 하지 않기 socket도 안 보내 지긴 하지만 (이건 연결후 테스트)

**Comment by minjune8506** [comment]
Time To Live?

**Comment by maindishes** [comment]
I dont know bro ,i have to searching it next day

**Comment by minjune8506** [comment]
gotcha

**Comment by maindishes** [comment]
- socket도 안 보내 지긴 하지만 (이건 연결후 테스트)
