### ISSUE TITLE
Redis / Bull Queue 사용 제거

### ISSUE THREAD

**Issue by minjune8506** [42-TRANSENDENCE/backend#89]
BullModule이 Redis를 사용하는 문제점.
- [x] BullModule 제거
- [x] Bull Queue를 사용하지 않고 API를 1초에 한번씩만 실행할 수 있게 변경

**Comment by maindishes** [comment]
저거 `API를 1초에 한번씩만 실행할 수 있게 변경`  이부분 초당 요청 횟수 제한 하는거 맞쥬 ?

**Comment by maindishes** [comment]
그 부분은 MiddleWare 로 모든 route에 적용 하도록 해놨습니당 
이 MiddleWare이용해서 로그인 안 하고 다른 페이지 접근 하는 거 막는 로직도 구현 할수 있을듯 하옵니다( 모든 api에  if문으로 토큰있나 확인하는방식이 아니라)

**Comment by minjune8506** [comment]
그거는 guard로 이미 구현해놨습니다 막는 기능

**Comment by minjune8506** [comment]
모든 route말고 login에만 적용하면 될것같아요

**Comment by maindishes** [comment]
그럼 로그인 쪽은 초당 1~2개? 로 제한 하고 나머진 좀 후하게 제한하는걸로 할까요? 제한하긴 해야하지 않나요?

**Comment by minjune8506** [comment]
@maindishes 나머지는 음.. 굳이 제한할 필요가 이쓸까.. 싶긴하네요 모르게써여

**Comment by minjune8506** [comment]
@maindishes 로그인은 초당 1개 요청만 제한하고 나중에 2개로 풀어서 잘 돌아가나 확인해봐야할거같아요
