### ISSUE TITLE
user search

### ISSUE THREAD

**Issue by minjune8506** [42-TRANSENDENCE/backend#96]
user search API 반환값 수정
- 친구인지 아닌지 를 나타낼 수 있는 데이터 추가

**Comment by keonwoo98** [comment]
* search 했을 때 그 사람의 avatar도 필요한데 같이 줄 수 있나요? 아님 따로 api 만든거에 요청해서 받아야하나요?
* 나중에 게임 전적(승, 패)이 생겼을 때 전적 정보도 받아야합니당. 내 정보 가져오는 `/users` 도 마찬가지.

**Comment by minjune8506** [comment]
- avatar 같이 반환 OK
- 친구 인지 확인하는 데이터 OK
- 게임 전적은 추후에 업데이트 할 예정

**Comment by minjune8506** [comment]
대신에 avatar도 함께 반환하면 header에 content-type과 같은 정보는 넣지 못함
알아서 파싱해서 사용해야함
@keonwoo98

**Comment by keonwoo98** [comment]
객체로 한 번에 주는거지?

**Comment by minjune8506** [comment]
@keonwoo98 맞음요 achievement도 같이 반환 예정

**Comment by keonwoo98** [comment]
확인👍

**Comment by minjune8506** [comment]
게임 기록 반환하는 기능도 추가함
